### ISSUE TITLE
Where is the project documentation?

### ISSUE THREAD

**Issue by hasantezcan** [emrullahcirit/Algoritma#1]
Hello Emrullah,
I want the see your program UIs and project details. You can express all these things with project documentation. If you add this document with README.md named in main project directory GitHub will show us your project document automatically on the main page.

**Comment by hasantezcan** [comment]
And I suggest publish it with English thus most people can understand your project scopes and purpose easily.

**Comment by emrullahcirit** [comment]
Hello Hasan,
Thank you for your advices. I will consider them and review my project as soon as possible.
